CREATE 
    ALGORITHM = UNDEFINED 
    SQL SECURITY DEFINER
VIEW `vw_generator_16` AS
    SELECT 0 AS `n` 
    UNION ALL SELECT 1 AS `1` 
    UNION ALL SELECT 2 AS `2` 
    UNION ALL SELECT 3 AS `3` 
    UNION ALL SELECT 4 AS `4` 
    UNION ALL SELECT 5 AS `5` 
    UNION ALL SELECT 6 AS `6` 
    UNION ALL SELECT 7 AS `7` 
    UNION ALL SELECT 8 AS `8` 
    UNION ALL SELECT 9 AS `9` 
    UNION ALL SELECT 10 AS `10` 
    UNION ALL SELECT 11 AS `11` 
    UNION ALL SELECT 12 AS `12` 
    UNION ALL SELECT 13 AS `13` 
    UNION ALL SELECT 14 AS `14` 
    UNION ALL SELECT 15 AS `15`
